Add publishing config
jellyfin/jellyfin-exoplayer-ffmpeg-extension pull request #1
Opened 2021-08-24 21:49 UTC by Maxr1998

2021-08-25 06:58 UTC, nielsvanvelzen commented
It tries to publish for this PR so that's definitely a problem :p

2021-08-25 09:53 UTC, Maxr1998 commented
Well, I thought that we could publish all master commits since we probably won't to version tags or something. But with the hardcoded ExoPlayer version it could be a problem..

2021-08-25 09:59 UTC, nielsvanvelzen commented
We do need releases because you can't overwrite an existing version on Maven Central (-SNAPSHOT is an exception to this).

2021-08-25 10:17 UTC, Maxr1998 commented
Yeah, I remembered that. Kinda oof. Should we append/prepend our own string to the ExoPlayer version maybe?

2021-08-25 10:30 UTC, nielsvanvelzen commented
Most projects use the Semver approach of appending a build number. So ExoPlayer `2.15.0` would become `2.15.0+1`, `2.15.0+2` etc.
I guess using tags like we do in android/atv/sdk is the best approach here to stay consistent and make sure we use the correct names.

2021-09-02 18:39 UTC, Maxr1998 commented
I reworked it to use the SDK's system of version tags, `v1.0.0` would become `2.15.0+1.0.0` for the current ExoPlayer version.

2021-09-02 19:32 UTC, nielsvanvelzen requested changes
If you publish locally can you confirm:

- There is a -sources.jar file
- There is a -javadoc.jar file

2021-09-02 19:32 UTC, nielsvanvelzen commented on exoplayer-ffmpeg-extension/build.gradle.kts
> +version = "$exoPlayerVersion+${createVersionSuffix()}"
Snapshot releases should end with `-SNAPSHOT`, right now it uses `+SNAPSHOT`. Same for build number.

https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401

2021-09-02 19:33 UTC, nielsvanvelzen commented on exoplayer-ffmpeg-extension/build.gradle.kts
> +version = "$exoPlayerVersion+${createVersionSuffix()}"
(I should've looked this up sooner :p)

2021-09-03 07:11 UTC, nielsvanvelzen approved these changes

2021-09-03 07:11 UTC, merged